# See https://pre-commit.com for more information
repos:
# Ruff pre-commit hooks.
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
    # Run the linter.
    -   id: ruff
        args: [ --fix ]
    # Run the formatter.
    -   id: ruff-format