name: Run tests and upload coverage to Codecov 📊

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Python version
        id: get-python-version
        run: |
            echo "PYTHON_VERSION=$(grep 'PYTHON_VERSION' Makefile.env | sed 's/PYTHON_VERSION=//')" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: poetry install
      - name: Run pytest
        run: make project/tests ARGS="--cov-report=json"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: ${{ github.repository }}
